/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 *
 * Regenerate: `npm run generate:types` (requires API running)
 */

export interface paths {
  "/api/Appointments": {
    get: {
      responses: {
        200: {
          content: {
            "text/json": components["schemas"]["Appointment"][];
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateAppointmentDto"];
        };
      };
      responses: {
        201: {
          content: {
            "text/json": components["schemas"]["Appointment"];
          };
        };
      };
    };
  };
  "/api/Appointments/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        200: {
          content: {
            "text/json": components["schemas"]["Appointment"];
          };
        };
        404: {
          content: never;
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: number;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateAppointmentDto"];
        };
      };
      responses: {
        200: {
          content: {
            "text/json": components["schemas"]["Appointment"];
          };
        };
        404: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        204: {
          content: never;
        };
        404: {
          content: never;
        };
      };
    };
  };
  "/api/Appointments/{id}/approve": {
    patch: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        200: {
          content: {
            "text/json": components["schemas"]["Appointment"];
          };
        };
        404: {
          content: never;
        };
      };
    };
  };
  "/api/Auth/login": {
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["LoginDto"];
        };
      };
      responses: {
        200: {
          content: {
            "text/json": {
              message?: string;
            };
          };
        };
        401: {
          content: {
            "text/json": {
              message?: string;
            };
          };
        };
      };
    };
  };
  "/api/Auth/logout": {
    post: {
      responses: {
        200: {
          content: {
            "text/json": {
              message?: string;
            };
          };
        };
      };
    };
  };
  "/api/Auth/me": {
    get: {
      responses: {
        200: {
          content: {
            "text/json": {
              email?: string;
            };
          };
        };
        401: {
          content: {
            "text/json": {
              message?: string;
            };
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    Appointment: {
      id: number;
      name: string;
      appointmentDateTime: string;
      description: string;
      contactNumber: string;
      emailAddress: string;
      status: number;
      createdAt: string;
    };
    AppointmentStatus: number;
    CreateAppointmentDto: {
      name: string;
      appointmentDateTime: string;
      description: string;
      contactNumber: string;
      emailAddress: string;
    };
    UpdateAppointmentDto: {
      name: string;
      appointmentDateTime: string;
      description: string;
      contactNumber: string;
      emailAddress: string;
    };
    LoginDto: {
      email: string;
      password: string;
    };
  };
}
